version: "3.8"

services:
  lighthouse-smartcontract:
    build:
      context: .
    container_name: "lighthouse-smartcontract"
    volumes:
      - type: bind
        source: ./
        target: /home/node/app/
      - /home/node/app/node_modules
    networks:
      - net
    entrypoint: sh
    command: '-c "sleep 1d"'
    env_file: 
      - ./.env
    cap_add:
      - IPC_LOCK
networks:
  net:
